name: Test

on:
  push:
    branches:
      - master
  pull_request:
    # Run on all PRs

env:
  CI: "true"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          ini-values: zend.assertions=1, assert.exception=1, error_reporting=-1
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer update
          --no-ansi
          --no-interaction
          --no-progress
          --no-suggest
          --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit
          --coverage-clover coverage.xml
          --coverage-text

      - name: Submit code coverage
        if: ${{ always() }}
        uses: codecov/codecov-action@v2
